# Loosely based on:
#     https://github.com/DarkMatterCore/nxdumptool/blob/rewrite-prerelease/.github/workflows/rewrite.yml
#     https://medium.com/@mellomello2030/write-a-github-actions-workflow-for-rust-cross-compilation-44284dfa9597
name: Build parcel

on:
    push:
        branches: ["master"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - rust_target: x86_64-unknown-linux-gnu
                      artifact_name: parcel-linux
                    - rust_target: x86_64-pc-windows-gnu
                      artifact_name: parcel-windows.exe
        steps:
            - uses: actions/checkout@v4

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
                  target: ${{ matrix.rust_target }}

            - name: Install evil MingW for Windows
              if: matrix.rust_target == 'x86_64-pc-windows-gnu'
              run: sudo apt-get install -y gcc-mingw-w64-x86–64

            - name: Build the binary
              run: |
                  cargo build -target ${{ matrix.rust_target }}
                  if [[ "${{ matrix.artifact_name }}" == *.exe ]]; then
                      mv target/${{ matrix.rust_target }}/debug/parcel.exe ${{ matrix.artifact_name }}
                  else
                      mv target/${{ matrix.rust_target }}/debug/parcel ${{ matrix.artifact_name }}
                  fi

            - name: Upload da build
              uses: actions/upload-artifact@v7.0.1
              with:
                  # A file, directory or wildcard pattern that describes what to upload.
                  path: ${{ matrix.artifact_name }}
                  if-no-files-found: error
